#!/usr/bin/env sh

# Shell script to automate Arch Linux's installation. It can be executed
# by running the following command inside a live media environment:
#
#   sh <(curl -Ls git.io/vzWco)

# Exits if any command or pipe fails, or if variables are unset.
set -e -u -o pipefail

# Wrapping the script inside curly brackets ensures it will be executed only
# if the closing bracket is reached, preventing undesired behavior if the
# connection is terminated when the script is being downloaded.
{
  prompt() {
    printf "%s" "$1"
    while read -r VAR ; do
      if echo "$VAR" | grep -Eqx "$3" || \
         [ "$3" -gt "$(echo "$VAR" | numfmt --from=iec)" ] ; then
        eval "$2='$VAR'"
        break
      else
        printf "Invalid input! Try again: "
      fi
    done
  }

  show() {
    printf "%s\n%s\n" "$1" "$(echo "$2" | column)"
  }

  { # disk partitioning
    show "Available disks:" "$(lsblk -dnpe 2,7,11 -o NAME,SIZE)"
    prompt "Choose the disk: " DISK "$(lsblk -dnpe 2,7,11 -o NAME)"

    MAX="$(lsblk -bdne 2,7,11 -o SIZE "$DISK")"
    prompt "Set the root partition size (max. $MAX): " ROOTSIZE "$MAX"

    [ -d "/sys/firmware/efi" ] && LABEL="gpt" || LABEL="msdos"
    parted -s --align optimal -- "$DISK" mklabel "$LABEL" \
      mkpart primary fat32 1M 50M \
      set 1 boot on \
      mkpart primary ext3 50M "$ROOTSIZE" \
      mkpart primary ext3 "$ROOTSIZE" 100%

    mkfs.vfat -F32 "${DISK}1"
    mkfs.ext4 "${DISK}2"
    mkfs.ext4 "${DISK}3"

    mount "${DISK}2" /mnt
    mkdir -p /mnt/boot
    mount "${DISK}1" /mnt/boot
  }

  { # mirror configuration and base system install
    MIRROR="$(curl -kLs "archlinux.org/mirrorlist/?use_mirror_status=on")"
    VALID_LOCATIONS="$(echo "$MIRROR" | awk -F", " '{print $2}' | sort -u)"

    show "Countries that host mirrors:" "$VALID_LOCATIONS"
    prompt "Country (or nearest location): " COUNTRY "$VALID_LOCATIONS"
    echo "$MIRROR" | sed "/$COUNTRY/{n;s/#S/S/}" > /etc/pacman.d/mirrorlist

    pacstrap /mnt base base-devel bash-completion expac pkgfile bc grub
    genfstab -U -p /mnt >> /mnt/etc/fstab
    cp -f /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
  }

  { # locale and timezone configuration
    VALID_LOCALES="$(grep -Eo "[a-z]+_[A-Z]+" /etc/locale.gen | sort -u)"
    show "Available locales:" "$VALID_LOCALES"
    prompt "Locale for the system: " LOCALE "$VALID_LOCALES"

    sed -i "s/#$LOCALE/$LOCALE/" /mnt/etc/locale.gen
    arch-chroot /mnt locale-gen
    echo "LANG=$(awk -v l="$LOCALE" '$0 ~ l {print $1; exit}' \
      /etc/locale.gen)" > /mnt/etc/locale.conf

    TIMEZONE="$(tzselect)"
    ln -sf "/usr/share/zoneinfo/$TIMEZONE" /mnt/etc/localtime
    arch-chroot /mnt hwclock --systohc --utc
  }

  { # hostname, user account and password configuration
    PATTERN="[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]"
    prompt "Enter the hostname: " HOST "($PATTERN)(\.($PATTERN)){0,3}"
    echo "$HOST" > /mnt/etc/hostname
    sed -i "7a 127.0.1.1\t$HOST.localdomain\t$HOST" /mnt/etc/hosts

    echo "Password for superuser:"
    arch-chroot /mnt passwd

    VALID_NAMES="[a-z_]([a-z0-9_]{,30}[$]|[a-z0-9_]{,31})"
    prompt "Enter the username: " USER "$VALID_NAMES"
    arch-chroot /mnt useradd -m -g users -G wheel "$USER"

    echo "Password for $USER:"
    arch-chroot /mnt passwd "$USER"
    echo "%wheel ALL=(ALL) ALL" > /mnt/etc/sudoers.d/99_enable_wheel
  }

  { # bootloader installation
    if [ -d "/sys/firmware/efi" ] ; then
      pacman -r /mnt -S --noconfirm efibootmgr
      arch-chroot /mnt grub-install --target=x86_64-efi \
        --efi-directory=/boot --bootloader-id=boot
    else
      arch-chroot /mnt grub-install --target=i386-pc "$DISK"
    fi
    arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
  }
}
